spring.application.name=graus

spring.datasource.url=jdbc:h2:mem:graus
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics,caches
management.info.env.enabled=true

info.app.name=70Graus API
info.app.description=API REST para controle de produtos, estoque, funcionarios e movimentacoes
info.app.version=1.0.0